site_name: Notes JSP
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Open Sans
    code: Fira Code
  icon: 
    logo: fontawesome/brands/java
  features:
    - navigation.footer
  palette: 
  # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep orange
  # Light moide
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: green
      accent: deep orange

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - admonition
  - pymdownx.details
  - toc:
      title: Table des matières
  - tables

nav:
  - Accueil: index.md
  - Servlets Java:
    - Architecture de Tomcat et des servlets: tomcat.md
    - Configuration d'un servlet: config-servlet.md
  - Annexes:
    - Annexe A - Dépendances Maven utiles: maven-dependences.md      

extra_css:
  - extra.css